fix deploy10

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -10,10 +10,6 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-        - name: Remove old stack
-        run: |
-          sls remove --stage dev
-
       - name: Checkout repository
         uses: actions/checkout@v3
 
@@ -26,7 +22,8 @@ jobs:
         run: npm install -g serverless@3
 
       - name: Install dependencies
-        run: npm install
+        run: |
+          npm install
           npm install mysql2
 
       - name: Build Vite App
@@ -44,5 +41,10 @@ jobs:
           echo "TOKEN_SECRET=${{ secrets.TOKEN_SECRET }}" >> $GITHUB_ENV
           echo "MONGO_KEY=${{ secrets.MONGO_KEY }}" >> $GITHUB_ENV
 
+      
+      - name: Remove CloudFormation Stack if it exists
+        run: serverless remove --stage dev || echo "Stack not found or already removed"
+
+      # Paso de despliegue
       - name: Deploy with Serverless v3
         run: serverless deploy
